spring:
  application:
    name: unit-06-eureka-server
  profiles:
    active: win

server:
  port: 1111

# eureka配置
eureka:
  client:
    # 是否向注册中心注册=false 自己就是注册中心
    fetch-registry: false
    # 不需要去检索服务
    register-with-eureka: false
    service-url:
      # eureka 服务地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # eureka server 自我保护机制:EMERGENCY! EUREKA MAY BE INCORRECTLY CLAIMING ......
    enable-self-preservation: false
  instance:
    hostname: localhost
    # 及时发现服务时效
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2


# 日志配置
logging:
  file: ../logs/${spring.application.name}.log
