spring:
  application:
    name: unit-06-micro-service-consumer
  profiles:
    active: win

# 服务器配置
server:
  port: 8080
  context-path: /${spring.application.name}/${spring.profiles.active}/

# 断路器配置
feign:
  hystrix:
    enabled: true

# eureka 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/

# 日志配置
logging:
  file: ../logs/${spring.application.name}.log


